version: '3.1'

services:
  client:
    image: bennythink/searchgram
    env_file:
      - env/gram.env
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./sg_data/session:/SearchGram/searchgram/session
    command:
      - client.py

  bot:
    image: bennythink/searchgram
    env_file:
      - env/gram.env
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./sg_data/session:/SearchGram/searchgram/session
    command:
      - bot.py

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - ./sg_data/mongodb:/data/db
    logging:
      driver: none
