name: docker image builder
on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower case for Docker Hub
        id: dh_string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

      - name: Lower case for ghcr
        id: ghcr_string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.repository.full_name }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm,linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.dh_string.outputs.lowercase }}:ng
            ghcr.io/${{ steps.ghcr_string.outputs.lowercase }}:ng

          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          envs: TOKEN
          host: ${{ secrets.PROD_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker save bennythink/searchgram:ng > /root/searchgram-old.tar
            docker pull bennythink/searchgram:ng
            docker-compose -f /home/SearchGram/docker-compose.yml up -d
            curl "https://api.telegram.org/bot$TOKEN/sendMessage?chat_id=260260121&text=SearchGram%20upgrade%20complete!"
            echo "SearchGram upgrade complete!"
